DROP FUNCTION IF EXISTS getBD_Seq;
DELIMITER $$
CREATE FUNCTION getBD_Seq( CATEG VARCHAR(30), BOARDTYPE VARCHAR(30))
	RETURNS INT
BEGIN
	DECLARE num INT;
	DECLARE cd VARCHAR(30);
	SET cd = 'NULL';
    SET num = -1;
    SELECT CT.CT_CODE INTO cd FROM TB_CATEG CT
    WHERE CT.CATEGORY = CATEG;
    IF(cd != 'NULL') THEN
		SELECT BD.SEQ INTO num FROM TB_BOARD BD
		INNER JOIN TB_CATEG CT
		ON BD.CT_CODE = CT.CT_CODE
		WHERE CT.CATEGORY = CATEG AND BD.BOARD_TYPE=BOARDTYPE ORDER BY SEQ DESC LIMIT 1;
		IF (num = -1) THEN
			SET num = 1;
		ELSE
			SET num = num + 1;
		END IF;
    ELSE
		SET num = -1;
	END IF;
    RETURN num;
END $$
DELIMITER ;