DROP FUNCTION IF EXISTS getID_Seq;
DELIMITER $$
CREATE FUNCTION getID_Seq( CATEG VARCHAR(30))
	RETURNS INT
BEGIN
	DECLARE num INT;
	DECLARE cd VARCHAR(30);
	SET cd = 'NULL';
    SET num = -1;
    SELECT CT.CODE INTO cd FROM TB_CATEG CT
    WHERE CT.CATEGORY = CATEG;
    IF(cd != 'NULL') THEN
		SELECT SEQ INTO num FROM TB_IDEA ID 
		INNER JOIN TB_CATEG CT
		ON ID.CT_CODE = CT.CODE
		WHERE CT.CATEGORY = CATEG ORDER BY SEQ DESC LIMIT 1;
		IF (num != -1) THEN
			SET num = num + 1;
		ELSE
			SET num = 1;
		END IF;
    ELSE
		SET num = -1;
	END IF;
    RETURN num;
END $$
DELIMITER ;